### ISSUE TITLE
请问你这这边目前运行咋样？是否有其他异常情况

### ISSUE THREAD

**Issue by hww-png** [hsuyelin/mosdns-openclash-adguradhome#2]

**Comment by hsuyelin** [comment]
用着挺好的，兼顾到广告过滤，科学上网，ipv6，我是小主机软路由J4125的配置

**Comment by hww-png** [comment]
adguardhome里面客户端为啥只显示一个192网段的客户端，其他的ip貌似看不到。![image](https://github.com/hsuyelin/mosdns-openclash-adguradhome/assets/77440291/825afae1-7497-481f-992a-338879c2929b)

> 用着挺好的，兼顾到广告过滤，科学上网，ipv6，我是小主机软路由J4125的配置

**Comment by hww-png** [comment]
有tg吗，方便交流一下。
> 用着挺好的，兼顾到广告过滤，科学上网，ipv6，我是小主机软路由J4125的配置
